//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmEbc
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8586")]
	public enum BookableResourceBookingState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Represents the line details of a resource booking.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("bookableresourcebooking")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8586")]
	public partial class BookableResourceBooking : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public struct Fields
		{
			public const string BookableResourceBookingId = "bookableresourcebookingid";
			public const string Id = "bookableresourcebookingid";
			public const string BookingStatus = "bookingstatus";
			public const string BookingType = "bookingtype";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string Duration = "duration";
			public const string EndTime = "endtime";
			public const string ExchangeRate = "exchangerate";
			public const string Header = "header";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_ActualArrivalTime = "msdyn_actualarrivaltime";
			public const string msdyn_ActualTravelDuration = "msdyn_actualtravelduration";
			public const string msdyn_AgreementBookingDate = "msdyn_agreementbookingdate";
			public const string msdyn_AllowOverlapping = "msdyn_allowoverlapping";
			public const string msdyn_BookingMethod = "msdyn_bookingmethod";
			public const string msdyn_BookingSetupMetadataId = "msdyn_bookingsetupmetadataid";
			public const string msdyn_CascadeCrewChanges = "msdyn_cascadecrewchanges";
			public const string msdyn_EstimatedArrivalTime = "msdyn_estimatedarrivaltime";
			public const string msdyn_EstimatedTravelDuration = "msdyn_estimatedtravelduration";
			public const string msdyn_InternalFlags = "msdyn_internalflags";
			public const string msdyn_Latitude = "msdyn_latitude";
			public const string msdyn_Longitude = "msdyn_longitude";
			public const string msdyn_MilesTraveled = "msdyn_milestraveled";
			public const string msdyn_PreventTimestampCreation = "msdyn_preventtimestampcreation";
			public const string msdyn_projectid = "msdyn_projectid";
			public const string msdyn_projectteamid = "msdyn_projectteamid";
			public const string msdyn_resourcecategoryid = "msdyn_resourcecategoryid";
			public const string msdyn_ResourceGroup = "msdyn_resourcegroup";
			public const string msdyn_ResourceRequirement = "msdyn_resourcerequirement";
			public const string msdyn_Signature = "msdyn_signature";
			public const string msdyn_SlotText = "msdyn_slottext";
			public const string msdyn_TimeGroupDetailSelected = "msdyn_timegroupdetailselected";
			public const string msdyn_TotalBillableDuration = "msdyn_totalbillableduration";
			public const string msdyn_TotalBreakDuration = "msdyn_totalbreakduration";
			public const string msdyn_TotalCost = "msdyn_totalcost";
			public const string msdyn_totalcost_Base = "msdyn_totalcost_base";
			public const string msdyn_TotalDurationInProgress = "msdyn_totaldurationinprogress";
			public const string msdyn_TravelTimeRescheduling = "msdyn_traveltimerescheduling";
			public const string msdyn_WorkOrder = "msdyn_workorder";
			public const string Name = "name";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string ProcessId = "processid";
			public const string Resource = "resource";
			public const string StageId = "stageid";
			public const string StartTime = "starttime";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string TraversedPath = "traversedpath";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string bookableresource_bookableresourcebooking_Resource = "bookableresource_bookableresourcebooking_Resource";
			public const string bookableresourcebookingheader_bookableresourcebooking_Header = "bookableresourcebookingheader_bookableresourcebooking_Header";
			public const string bookingstatus_bookableresourcebooking_BookingStatus = "bookingstatus_bookableresourcebooking_BookingStatus";
			public const string business_unit_bookableresourcebooking = "business_unit_bookableresourcebooking";
			public const string lk_bookableresourcebooking_createdby = "lk_bookableresourcebooking_createdby";
			public const string lk_bookableresourcebooking_createdonbehalfby = "lk_bookableresourcebooking_createdonbehalfby";
			public const string lk_bookableresourcebooking_modifiedby = "lk_bookableresourcebooking_modifiedby";
			public const string lk_bookableresourcebooking_modifiedonbehalfby = "lk_bookableresourcebooking_modifiedonbehalfby";
			public const string msdyn_bookableresource_bookableresourcebooking_ResourceGroup = "msdyn_bookableresource_bookableresourcebooking_ResourceGroup";
			public const string msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid = "msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid";
			public const string msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate = "msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate";
			public const string msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking = "msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking";
			public const string msdyn_msdyn_project_bookableresourcebooking_projectid = "msdyn_msdyn_project_bookableresourcebooking_projectid";
			public const string msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid = "msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid";
			public const string msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected = "msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected";
			public const string msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder = "msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder";
			public const string msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement = "msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement";
			public const string team_bookableresourcebooking = "team_bookableresourcebooking";
			public const string TransactionCurrency_bookableresourcebooking = "TransactionCurrency_bookableresourcebooking";
			public const string user_bookableresourcebooking = "user_bookableresourcebooking";
		}

		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BookableResourceBooking() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "bookableresourcebooking";
		
		public const int EntityTypeCode = 1145;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the resource booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookableresourcebookingid")]
		public System.Nullable<System.Guid> BookableResourceBookingId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("bookableresourcebookingid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookableResourceBookingId");
				this.SetAttributeValue("bookableresourcebookingid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("BookableResourceBookingId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookableresourcebookingid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.BookableResourceBookingId = value;
			}
		}
		
		/// <summary>
		/// Select the status of the booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookingstatus")]
		public Microsoft.Xrm.Sdk.EntityReference BookingStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("bookingstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookingStatus");
				this.SetAttributeValue("bookingstatus", value);
				this.OnPropertyChanged("BookingStatus");
			}
		}
		
		/// <summary>
		/// Select whether the booking is solid or liquid. Solid bookings are firm and cannot be changed whereas liquid bookings can be changed.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookingtype")]
		public object BookingType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("bookingtype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookingType");
				this.SetAttributeValue("bookingtype", value);
				this.OnPropertyChanged("BookingType");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Enter the duration of the booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("duration")]
		public System.Nullable<int> Duration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("duration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Duration");
				this.SetAttributeValue("duration", value);
				this.OnPropertyChanged("Duration");
			}
		}
		
		/// <summary>
		/// Enter the end date and time of the booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("endtime")]
		public System.Nullable<System.DateTime> EndTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("endtime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("EndTime");
				this.SetAttributeValue("endtime", value);
				this.OnPropertyChanged("EndTime");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the bookableresourcebooking with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Shows the reference to the booking header record that represents the summary of bookings.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("header")]
		public Microsoft.Xrm.Sdk.EntityReference Header
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("header");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Header");
				this.SetAttributeValue("header", value);
				this.OnPropertyChanged("Header");
			}
		}
		
		/// <summary>
		/// Sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Date and time when the record was modified.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Unique identifier of the delegate user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the time that work started.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_actualarrivaltime")]
		public System.Nullable<System.DateTime> msdyn_ActualArrivalTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_actualarrivaltime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ActualArrivalTime");
				this.SetAttributeValue("msdyn_actualarrivaltime", value);
				this.OnPropertyChanged("msdyn_ActualArrivalTime");
			}
		}
		
		/// <summary>
		/// Shows the total travel duration. If you leave this field blank the system automatically determines the travel duration by calculating the resource journal details.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_actualtravelduration")]
		public System.Nullable<int> msdyn_ActualTravelDuration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_actualtravelduration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ActualTravelDuration");
				this.SetAttributeValue("msdyn_actualtravelduration", value);
				this.OnPropertyChanged("msdyn_ActualTravelDuration");
			}
		}
		
		/// <summary>
		/// Agreement Booking Date from where this Booking was generated
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_agreementbookingdate")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_AgreementBookingDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_agreementbookingdate");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AgreementBookingDate");
				this.SetAttributeValue("msdyn_agreementbookingdate", value);
				this.OnPropertyChanged("msdyn_AgreementBookingDate");
			}
		}
		
		/// <summary>
		/// Allow the time of this booking to be displayed on the schedule assistant as available.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_allowoverlapping")]
		public System.Nullable<bool> msdyn_AllowOverlapping
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_allowoverlapping");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_AllowOverlapping");
				this.SetAttributeValue("msdyn_allowoverlapping", value);
				this.OnPropertyChanged("msdyn_AllowOverlapping");
			}
		}
		
		/// <summary>
		/// Shows the method used to create this booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookingmethod")]
		public object msdyn_BookingMethod
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("msdyn_bookingmethod");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BookingMethod");
				this.SetAttributeValue("msdyn_bookingmethod", value);
				this.OnPropertyChanged("msdyn_BookingMethod");
			}
		}
		
		/// <summary>
		/// A unique identifier for the booking setup metadata that is associated with a bookable resource booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookingsetupmetadataid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_BookingSetupMetadataId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_bookingsetupmetadataid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_BookingSetupMetadataId");
				this.SetAttributeValue("msdyn_bookingsetupmetadataid", value);
				this.OnPropertyChanged("msdyn_BookingSetupMetadataId");
			}
		}
		
		/// <summary>
		/// Defines whether changing any of the following fields (Start Time, End Time, Status) should cascade the changes to other bookings on this requirement that have the same start and end time.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_cascadecrewchanges")]
		public System.Nullable<bool> msdyn_CascadeCrewChanges
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_cascadecrewchanges");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_CascadeCrewChanges");
				this.SetAttributeValue("msdyn_cascadecrewchanges", value);
				this.OnPropertyChanged("msdyn_CascadeCrewChanges");
			}
		}
		
		/// <summary>
		/// Estimated Arrival Time
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_estimatedarrivaltime")]
		public System.Nullable<System.DateTime> msdyn_EstimatedArrivalTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_estimatedarrivaltime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_EstimatedArrivalTime");
				this.SetAttributeValue("msdyn_estimatedarrivaltime", value);
				this.OnPropertyChanged("msdyn_EstimatedArrivalTime");
			}
		}
		
		/// <summary>
		/// Estimated Travel Duration
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_estimatedtravelduration")]
		public System.Nullable<int> msdyn_EstimatedTravelDuration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_estimatedtravelduration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_EstimatedTravelDuration");
				this.SetAttributeValue("msdyn_estimatedtravelduration", value);
				this.OnPropertyChanged("msdyn_EstimatedTravelDuration");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_internalflags")]
		public string msdyn_InternalFlags
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_internalflags");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_InternalFlags");
				this.SetAttributeValue("msdyn_internalflags", value);
				this.OnPropertyChanged("msdyn_InternalFlags");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_latitude")]
		public System.Nullable<double> msdyn_Latitude
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("msdyn_latitude");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Latitude");
				this.SetAttributeValue("msdyn_latitude", value);
				this.OnPropertyChanged("msdyn_Latitude");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_longitude")]
		public System.Nullable<double> msdyn_Longitude
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("msdyn_longitude");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Longitude");
				this.SetAttributeValue("msdyn_longitude", value);
				this.OnPropertyChanged("msdyn_Longitude");
			}
		}
		
		/// <summary>
		/// In this field you can enter the total miles the resource drove to the job site
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_milestraveled")]
		public System.Nullable<double> msdyn_MilesTraveled
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<double>>("msdyn_milestraveled");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_MilesTraveled");
				this.SetAttributeValue("msdyn_milestraveled", value);
				this.OnPropertyChanged("msdyn_MilesTraveled");
			}
		}
		
		/// <summary>
		/// Prevents time stamp creation if the time stamp was already created on a mobile device.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_preventtimestampcreation")]
		public System.Nullable<bool> msdyn_PreventTimestampCreation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_preventtimestampcreation");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_PreventTimestampCreation");
				this.SetAttributeValue("msdyn_preventtimestampcreation", value);
				this.OnPropertyChanged("msdyn_PreventTimestampCreation");
			}
		}
		
		/// <summary>
		/// Project of booking detail record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_projectid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_projectid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_projectid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_projectid");
				this.SetAttributeValue("msdyn_projectid", value);
				this.OnPropertyChanged("msdyn_projectid");
			}
		}
		
		/// <summary>
		/// Project team member of booking detail record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_projectteamid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_projectteamid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_projectteamid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_projectteamid");
				this.SetAttributeValue("msdyn_projectteamid", value);
				this.OnPropertyChanged("msdyn_projectteamid");
			}
		}
		
		/// <summary>
		/// Resource Category
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcecategoryid")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_resourcecategoryid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_resourcecategoryid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_resourcecategoryid");
				this.SetAttributeValue("msdyn_resourcecategoryid", value);
				this.OnPropertyChanged("msdyn_resourcecategoryid");
			}
		}
		
		/// <summary>
		/// Unique identifier for Resource associated with Resource Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcegroup")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ResourceGroup
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_resourcegroup");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ResourceGroup");
				this.SetAttributeValue("msdyn_resourcegroup", value);
				this.OnPropertyChanged("msdyn_ResourceGroup");
			}
		}
		
		/// <summary>
		/// Resource Requirement
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcerequirement")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_ResourceRequirement
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_resourcerequirement");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_ResourceRequirement");
				this.SetAttributeValue("msdyn_resourcerequirement", value);
				this.OnPropertyChanged("msdyn_ResourceRequirement");
			}
		}
		
		/// <summary>
		/// This field is used for capturing signature on MoCa (using the Pen Control)
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_signature")]
		public string msdyn_Signature
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_signature");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Signature");
				this.SetAttributeValue("msdyn_signature", value);
				this.OnPropertyChanged("msdyn_Signature");
			}
		}
		
		/// <summary>
		/// Shows the automatically generated text of the time slot on the schedule board.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_slottext")]
		public string msdyn_SlotText
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_slottext");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_SlotText");
				this.SetAttributeValue("msdyn_slottext", value);
				this.OnPropertyChanged("msdyn_SlotText");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_timegroupdetailselected")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_TimeGroupDetailSelected
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_timegroupdetailselected");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TimeGroupDetailSelected");
				this.SetAttributeValue("msdyn_timegroupdetailselected", value);
				this.OnPropertyChanged("msdyn_TimeGroupDetailSelected");
			}
		}
		
		/// <summary>
		/// Shows the total billable duration. If you leave this field blank the system automatically determines the billable duration by calculating the resource journal details.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_totalbillableduration")]
		public System.Nullable<int> msdyn_TotalBillableDuration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_totalbillableduration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TotalBillableDuration");
				this.SetAttributeValue("msdyn_totalbillableduration", value);
				this.OnPropertyChanged("msdyn_TotalBillableDuration");
			}
		}
		
		/// <summary>
		/// Shows the total break duration. If you leave this field blank the system automatically determines the break duration by calculating the resource journal details.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_totalbreakduration")]
		public System.Nullable<int> msdyn_TotalBreakDuration
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_totalbreakduration");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TotalBreakDuration");
				this.SetAttributeValue("msdyn_totalbreakduration", value);
				this.OnPropertyChanged("msdyn_TotalBreakDuration");
			}
		}
		
		/// <summary>
		/// Shows the total cost for this booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_totalcost")]
		public Microsoft.Xrm.Sdk.Money msdyn_TotalCost
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_totalcost");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TotalCost");
				this.SetAttributeValue("msdyn_totalcost", value);
				this.OnPropertyChanged("msdyn_TotalCost");
			}
		}
		
		/// <summary>
		/// Value of the Total Cost in base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_totalcost_base")]
		public Microsoft.Xrm.Sdk.Money msdyn_totalcost_Base
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.Money>("msdyn_totalcost_base");
			}
		}
		
		/// <summary>
		/// Shows the total duration that this booking was in progress.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_totaldurationinprogress")]
		public System.Nullable<int> msdyn_TotalDurationInProgress
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("msdyn_totaldurationinprogress");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TotalDurationInProgress");
				this.SetAttributeValue("msdyn_totaldurationinprogress", value);
				this.OnPropertyChanged("msdyn_TotalDurationInProgress");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_traveltimerescheduling")]
		public System.Nullable<bool> msdyn_TravelTimeRescheduling
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_traveltimerescheduling");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TravelTimeRescheduling");
				this.SetAttributeValue("msdyn_traveltimerescheduling", value);
				this.OnPropertyChanged("msdyn_TravelTimeRescheduling");
			}
		}
		
		/// <summary>
		/// Unique identifier for Work Order associated with Resource Booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_workorder")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_WorkOrder
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_workorder");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_WorkOrder");
				this.SetAttributeValue("msdyn_workorder", value);
				this.OnPropertyChanged("msdyn_WorkOrder");
			}
		}
		
		/// <summary>
		/// Type a name for the booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user or team who owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Shows the ID of the process.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("processid")]
		public System.Nullable<System.Guid> ProcessId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("processid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ProcessId");
				this.SetAttributeValue("processid", value);
				this.OnPropertyChanged("ProcessId");
			}
		}
		
		/// <summary>
		/// Shows the resource that is booked.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resource")]
		public Microsoft.Xrm.Sdk.EntityReference Resource
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("resource");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Resource");
				this.SetAttributeValue("resource", value);
				this.OnPropertyChanged("Resource");
			}
		}
		
		/// <summary>
		/// Shows the ID of the stage.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("stageid")]
		public System.Nullable<System.Guid> StageId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("stageid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StageId");
				this.SetAttributeValue("stageid", value);
				this.OnPropertyChanged("StageId");
			}
		}
		
		/// <summary>
		/// Enter the start date and time of the booking.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("starttime")]
		public System.Nullable<System.DateTime> StartTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("starttime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StartTime");
				this.SetAttributeValue("starttime", value);
				this.OnPropertyChanged("StartTime");
			}
		}
		
		/// <summary>
		/// Status of the Bookable Resource Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<XrmEbc.BookableResourceBookingState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((XrmEbc.BookableResourceBookingState)(System.Enum.ToObject(typeof(XrmEbc.BookableResourceBookingState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value.Value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Bookable Resource Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public object StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Exchange rate for the currency associated with the BookableResourceBooking with respect to the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrencyId");
				this.SetAttributeValue("transactioncurrencyid", value);
				this.OnPropertyChanged("TransactionCurrencyId");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("traversedpath")]
		public string TraversedPath
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("traversedpath");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TraversedPath");
				this.SetAttributeValue("traversedpath", value);
				this.OnPropertyChanged("TraversedPath");
			}
		}
		
		/// <summary>
		/// Time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ActivityPointer> bookableresourcebooking_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ActivityPointer>("bookableresourcebooking_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_ActivityPointers");
				this.SetRelatedEntities<XrmEbc.ActivityPointer>("bookableresourcebooking_ActivityPointers", null, value);
				this.OnPropertyChanged("bookableresourcebooking_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_adx_alertsubscriptions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_adx_alertsubscriptions")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_alertsubscription> bookableresourcebooking_adx_alertsubscriptions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_alertsubscription>("bookableresourcebooking_adx_alertsubscriptions", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_adx_alertsubscriptions");
				this.SetRelatedEntities<XrmEbc.adx_alertsubscription>("bookableresourcebooking_adx_alertsubscriptions", null, value);
				this.OnPropertyChanged("bookableresourcebooking_adx_alertsubscriptions");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_adx_inviteredemptions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_adx_inviteredemptions")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_inviteredemption> bookableresourcebooking_adx_inviteredemptions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_inviteredemption>("bookableresourcebooking_adx_inviteredemptions", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_adx_inviteredemptions");
				this.SetRelatedEntities<XrmEbc.adx_inviteredemption>("bookableresourcebooking_adx_inviteredemptions", null, value);
				this.OnPropertyChanged("bookableresourcebooking_adx_inviteredemptions");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_adx_portalcomments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_adx_portalcomments")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_portalcomment> bookableresourcebooking_adx_portalcomments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_portalcomment>("bookableresourcebooking_adx_portalcomments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_adx_portalcomments");
				this.SetRelatedEntities<XrmEbc.adx_portalcomment>("bookableresourcebooking_adx_portalcomments", null, value);
				this.OnPropertyChanged("bookableresourcebooking_adx_portalcomments");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_Annotations")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Annotation> bookableresourcebooking_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Annotation>("bookableresourcebooking_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_Annotations");
				this.SetRelatedEntities<XrmEbc.Annotation>("bookableresourcebooking_Annotations", null, value);
				this.OnPropertyChanged("bookableresourcebooking_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_Appointments")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Appointment> bookableresourcebooking_Appointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Appointment>("bookableresourcebooking_Appointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_Appointments");
				this.SetRelatedEntities<XrmEbc.Appointment>("bookableresourcebooking_Appointments", null, value);
				this.OnPropertyChanged("bookableresourcebooking_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<XrmEbc.AsyncOperation> bookableresourcebooking_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.AsyncOperation>("bookableresourcebooking_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_AsyncOperations");
				this.SetRelatedEntities<XrmEbc.AsyncOperation>("bookableresourcebooking_AsyncOperations", null, value);
				this.OnPropertyChanged("bookableresourcebooking_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<XrmEbc.BulkDeleteFailure> bookableresourcebooking_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.BulkDeleteFailure>("bookableresourcebooking_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_BulkDeleteFailures");
				this.SetRelatedEntities<XrmEbc.BulkDeleteFailure>("bookableresourcebooking_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("bookableresourcebooking_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<XrmEbc.DuplicateRecord> bookableresourcebooking_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.DuplicateRecord>("bookableresourcebooking_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_DuplicateBaseRecord");
				this.SetRelatedEntities<XrmEbc.DuplicateRecord>("bookableresourcebooking_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("bookableresourcebooking_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<XrmEbc.DuplicateRecord> bookableresourcebooking_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.DuplicateRecord>("bookableresourcebooking_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_DuplicateMatchingRecord");
				this.SetRelatedEntities<XrmEbc.DuplicateRecord>("bookableresourcebooking_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("bookableresourcebooking_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_Emails")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Email> bookableresourcebooking_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Email>("bookableresourcebooking_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_Emails");
				this.SetRelatedEntities<XrmEbc.Email>("bookableresourcebooking_Emails", null, value);
				this.OnPropertyChanged("bookableresourcebooking_Emails");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_Faxes")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Fax> bookableresourcebooking_Faxes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Fax>("bookableresourcebooking_Faxes", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_Faxes");
				this.SetRelatedEntities<XrmEbc.Fax>("bookableresourcebooking_Faxes", null, value);
				this.OnPropertyChanged("bookableresourcebooking_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_Letters")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Letter> bookableresourcebooking_Letters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Letter>("bookableresourcebooking_Letters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_Letters");
				this.SetRelatedEntities<XrmEbc.Letter>("bookableresourcebooking_Letters", null, value);
				this.OnPropertyChanged("bookableresourcebooking_Letters");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<XrmEbc.MailboxTrackingFolder> bookableresourcebooking_MailboxTrackingFolders
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.MailboxTrackingFolder>("bookableresourcebooking_MailboxTrackingFolders", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_MailboxTrackingFolders");
				this.SetRelatedEntities<XrmEbc.MailboxTrackingFolder>("bookableresourcebooking_MailboxTrackingFolders", null, value);
				this.OnPropertyChanged("bookableresourcebooking_MailboxTrackingFolders");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_msdyn_approvals
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_msdyn_approvals")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_approval> bookableresourcebooking_msdyn_approvals
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_approval>("bookableresourcebooking_msdyn_approvals", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_msdyn_approvals");
				this.SetRelatedEntities<XrmEbc.msdyn_approval>("bookableresourcebooking_msdyn_approvals", null, value);
				this.OnPropertyChanged("bookableresourcebooking_msdyn_approvals");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_msdyn_bookingalerts
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_msdyn_bookingalerts")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_bookingalert> bookableresourcebooking_msdyn_bookingalerts
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_bookingalert>("bookableresourcebooking_msdyn_bookingalerts", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_msdyn_bookingalerts");
				this.SetRelatedEntities<XrmEbc.msdyn_bookingalert>("bookableresourcebooking_msdyn_bookingalerts", null, value);
				this.OnPropertyChanged("bookableresourcebooking_msdyn_bookingalerts");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_msdyn_surveyinvites
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_msdyn_surveyinvites")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_surveyinvite> bookableresourcebooking_msdyn_surveyinvites
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_surveyinvite>("bookableresourcebooking_msdyn_surveyinvites", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_msdyn_surveyinvites");
				this.SetRelatedEntities<XrmEbc.msdyn_surveyinvite>("bookableresourcebooking_msdyn_surveyinvites", null, value);
				this.OnPropertyChanged("bookableresourcebooking_msdyn_surveyinvites");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<XrmEbc.PhoneCall> bookableresourcebooking_PhoneCalls
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.PhoneCall>("bookableresourcebooking_PhoneCalls", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_PhoneCalls");
				this.SetRelatedEntities<XrmEbc.PhoneCall>("bookableresourcebooking_PhoneCalls", null, value);
				this.OnPropertyChanged("bookableresourcebooking_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_PrincipalObjectAttributeAccess
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_PrincipalObjectAttributeAccess")]
		public System.Collections.Generic.IEnumerable<XrmEbc.PrincipalObjectAttributeAccess> bookableresourcebooking_PrincipalObjectAttributeAccess
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.PrincipalObjectAttributeAccess>("bookableresourcebooking_PrincipalObjectAttributeAccess", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_PrincipalObjectAttributeAccess");
				this.SetRelatedEntities<XrmEbc.PrincipalObjectAttributeAccess>("bookableresourcebooking_PrincipalObjectAttributeAccess", null, value);
				this.OnPropertyChanged("bookableresourcebooking_PrincipalObjectAttributeAccess");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_ProcessSession")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ProcessSession> bookableresourcebooking_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ProcessSession>("bookableresourcebooking_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_ProcessSession");
				this.SetRelatedEntities<XrmEbc.ProcessSession>("bookableresourcebooking_ProcessSession", null, value);
				this.OnPropertyChanged("bookableresourcebooking_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<XrmEbc.RecurringAppointmentMaster> bookableresourcebooking_RecurringAppointmentMasters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.RecurringAppointmentMaster>("bookableresourcebooking_RecurringAppointmentMasters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_RecurringAppointmentMasters");
				this.SetRelatedEntities<XrmEbc.RecurringAppointmentMaster>("bookableresourcebooking_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("bookableresourcebooking_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_ServiceAppointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_ServiceAppointments")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ServiceAppointment> bookableresourcebooking_ServiceAppointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ServiceAppointment>("bookableresourcebooking_ServiceAppointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_ServiceAppointments");
				this.SetRelatedEntities<XrmEbc.ServiceAppointment>("bookableresourcebooking_ServiceAppointments", null, value);
				this.OnPropertyChanged("bookableresourcebooking_ServiceAppointments");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_SocialActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_SocialActivities")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SocialActivity> bookableresourcebooking_SocialActivities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SocialActivity>("bookableresourcebooking_SocialActivities", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_SocialActivities");
				this.SetRelatedEntities<XrmEbc.SocialActivity>("bookableresourcebooking_SocialActivities", null, value);
				this.OnPropertyChanged("bookableresourcebooking_SocialActivities");
			}
		}
		
		/// <summary>
		/// 1:N BookableResourceBooking_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("BookableResourceBooking_SyncErrors")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SyncError> BookableResourceBooking_SyncErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SyncError>("BookableResourceBooking_SyncErrors", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BookableResourceBooking_SyncErrors");
				this.SetRelatedEntities<XrmEbc.SyncError>("BookableResourceBooking_SyncErrors", null, value);
				this.OnPropertyChanged("BookableResourceBooking_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_Tasks")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Task> bookableresourcebooking_Tasks
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Task>("bookableresourcebooking_Tasks", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_Tasks");
				this.SetRelatedEntities<XrmEbc.Task>("bookableresourcebooking_Tasks", null, value);
				this.OnPropertyChanged("bookableresourcebooking_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N bookableresourcebooking_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebooking_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<XrmEbc.UserEntityInstanceData> bookableresourcebooking_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.UserEntityInstanceData>("bookableresourcebooking_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebooking_UserEntityInstanceDatas");
				this.SetRelatedEntities<XrmEbc.UserEntityInstanceData>("bookableresourcebooking_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("bookableresourcebooking_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_bookingjournal> msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_bookingjournal>("msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking");
				this.SetRelatedEntities<XrmEbc.msdyn_bookingjournal>("msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_bookingjournal_Booking");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_bookingtimestamp> msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_bookingtimestamp>("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking");
				this.SetRelatedEntities<XrmEbc.msdyn_bookingtimestamp>("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_purchaseorder> msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_purchaseorder>("msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking");
				this.SetRelatedEntities<XrmEbc.msdyn_purchaseorder>("msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_purchaseorder_Booking");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_purchaseorderproduct> msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_purchaseorderproduct>("msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking");
				this.SetRelatedEntities<XrmEbc.msdyn_purchaseorderproduct>("msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_purchaseorderproduct_AssociateToBooking");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBooking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBookin" +
			"g")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_purchaseorderreceiptproduct> msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBooking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_purchaseorderreceiptproduct>("msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBookin" +
						"g", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBookin" +
						"g");
				this.SetRelatedEntities<XrmEbc.msdyn_purchaseorderreceiptproduct>("msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBookin" +
						"g", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_purchaseorderreceiptproduct_AssociateToBookin" +
						"g");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_rtv_Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_rtv_Booking")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_rtv> msdyn_bookableresourcebooking_msdyn_rtv_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_rtv>("msdyn_bookableresourcebooking_msdyn_rtv_Booking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_rtv_Booking");
				this.SetRelatedEntities<XrmEbc.msdyn_rtv>("msdyn_bookableresourcebooking_msdyn_rtv_Booking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_rtv_Booking");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_workorderproduct> msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_workorderproduct>("msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking");
				this.SetRelatedEntities<XrmEbc.msdyn_workorderproduct>("msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_workorderproduct_Booking");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_workorderservice_Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_workorderservice_Booking")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_workorderservice> msdyn_bookableresourcebooking_msdyn_workorderservice_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_workorderservice>("msdyn_bookableresourcebooking_msdyn_workorderservice_Booking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_workorderservice_Booking");
				this.SetRelatedEntities<XrmEbc.msdyn_workorderservice>("msdyn_bookableresourcebooking_msdyn_workorderservice_Booking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_workorderservice_Booking");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_workorderservicetask> msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_workorderservicetask>("msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking");
				this.SetRelatedEntities<XrmEbc.msdyn_workorderservicetask>("msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_workorderservicetask_Booking");
			}
		}
		
		/// <summary>
		/// N:1 bookableresource_bookableresourcebooking_Resource
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("resource")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresource_bookableresourcebooking_Resource")]
		public XrmEbc.BookableResource bookableresource_bookableresourcebooking_Resource
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BookableResource>("bookableresource_bookableresourcebooking_Resource", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresource_bookableresourcebooking_Resource");
				this.SetRelatedEntity<XrmEbc.BookableResource>("bookableresource_bookableresourcebooking_Resource", null, value);
				this.OnPropertyChanged("bookableresource_bookableresourcebooking_Resource");
			}
		}
		
		/// <summary>
		/// N:1 bookableresourcebookingheader_bookableresourcebooking_Header
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("header")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookableresourcebookingheader_bookableresourcebooking_Header")]
		public XrmEbc.BookableResourceBookingHeader bookableresourcebookingheader_bookableresourcebooking_Header
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BookableResourceBookingHeader>("bookableresourcebookingheader_bookableresourcebooking_Header", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookableresourcebookingheader_bookableresourcebooking_Header");
				this.SetRelatedEntity<XrmEbc.BookableResourceBookingHeader>("bookableresourcebookingheader_bookableresourcebooking_Header", null, value);
				this.OnPropertyChanged("bookableresourcebookingheader_bookableresourcebooking_Header");
			}
		}
		
		/// <summary>
		/// N:1 bookingstatus_bookableresourcebooking_BookingStatus
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("bookingstatus")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("bookingstatus_bookableresourcebooking_BookingStatus")]
		public XrmEbc.BookingStatus bookingstatus_bookableresourcebooking_BookingStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BookingStatus>("bookingstatus_bookableresourcebooking_BookingStatus", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("bookingstatus_bookableresourcebooking_BookingStatus");
				this.SetRelatedEntity<XrmEbc.BookingStatus>("bookingstatus_bookableresourcebooking_BookingStatus", null, value);
				this.OnPropertyChanged("bookingstatus_bookableresourcebooking_BookingStatus");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_bookableresourcebooking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_bookableresourcebooking")]
		public XrmEbc.BusinessUnit business_unit_bookableresourcebooking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BusinessUnit>("business_unit_bookableresourcebooking", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcebooking_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcebooking_createdby")]
		public XrmEbc.SystemUser lk_bookableresourcebooking_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_bookableresourcebooking_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcebooking_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcebooking_createdonbehalfby")]
		public XrmEbc.SystemUser lk_bookableresourcebooking_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_bookableresourcebooking_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_bookableresourcebooking_createdonbehalfby");
				this.SetRelatedEntity<XrmEbc.SystemUser>("lk_bookableresourcebooking_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_bookableresourcebooking_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcebooking_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcebooking_modifiedby")]
		public XrmEbc.SystemUser lk_bookableresourcebooking_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_bookableresourcebooking_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_bookableresourcebooking_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_bookableresourcebooking_modifiedonbehalfby")]
		public XrmEbc.SystemUser lk_bookableresourcebooking_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_bookableresourcebooking_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_bookableresourcebooking_modifiedonbehalfby");
				this.SetRelatedEntity<XrmEbc.SystemUser>("lk_bookableresourcebooking_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_bookableresourcebooking_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_bookableresource_bookableresourcebooking_ResourceGroup
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcegroup")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresource_bookableresourcebooking_ResourceGroup")]
		public XrmEbc.BookableResource msdyn_bookableresource_bookableresourcebooking_ResourceGroup
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BookableResource>("msdyn_bookableresource_bookableresourcebooking_ResourceGroup", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresource_bookableresourcebooking_ResourceGroup");
				this.SetRelatedEntity<XrmEbc.BookableResource>("msdyn_bookableresource_bookableresourcebooking_ResourceGroup", null, value);
				this.OnPropertyChanged("msdyn_bookableresource_bookableresourcebooking_ResourceGroup");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcecategoryid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid")]
		public XrmEbc.BookableResourceCategory msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BookableResourceCategory>("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid");
				this.SetRelatedEntity<XrmEbc.BookableResourceCategory>("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcecategory_bookableresourcebooking_resourcecategoryid");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_agreementbookingdate")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate")]
		public XrmEbc.msdyn_agreementbookingdate msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.msdyn_agreementbookingdate>("msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate");
				this.SetRelatedEntity<XrmEbc.msdyn_agreementbookingdate>("msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate", null, value);
				this.OnPropertyChanged("msdyn_msdyn_agreementbookingdate_bookableresourcebooking_AgreementBookingDate");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookingsetupmetadataid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking")]
		public XrmEbc.msdyn_bookingsetupmetadata msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.msdyn_bookingsetupmetadata>("msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking");
				this.SetRelatedEntity<XrmEbc.msdyn_bookingsetupmetadata>("msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking", null, value);
				this.OnPropertyChanged("msdyn_msdyn_bookingsetupmetadata_bookableresourcebooking");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_project_bookableresourcebooking_projectid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_projectid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_project_bookableresourcebooking_projectid")]
		public XrmEbc.msdyn_project msdyn_msdyn_project_bookableresourcebooking_projectid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.msdyn_project>("msdyn_msdyn_project_bookableresourcebooking_projectid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_project_bookableresourcebooking_projectid");
				this.SetRelatedEntity<XrmEbc.msdyn_project>("msdyn_msdyn_project_bookableresourcebooking_projectid", null, value);
				this.OnPropertyChanged("msdyn_msdyn_project_bookableresourcebooking_projectid");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_projectteamid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid")]
		public XrmEbc.msdyn_projectteam msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.msdyn_projectteam>("msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid");
				this.SetRelatedEntity<XrmEbc.msdyn_projectteam>("msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid", null, value);
				this.OnPropertyChanged("msdyn_msdyn_projectteam_bookableresourcebooking_projectteamid");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_timegroupdetailselected")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected")]
		public XrmEbc.msdyn_timegroupdetail msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.msdyn_timegroupdetail>("msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected");
				this.SetRelatedEntity<XrmEbc.msdyn_timegroupdetail>("msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected", null, value);
				this.OnPropertyChanged("msdyn_msdyn_timegroupdetail_bookableresourcebooking_TimeGroupDetailSelected");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_workorder")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder")]
		public XrmEbc.msdyn_workorder msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.msdyn_workorder>("msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder");
				this.SetRelatedEntity<XrmEbc.msdyn_workorder>("msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder", null, value);
				this.OnPropertyChanged("msdyn_msdyn_workorder_bookableresourcebooking_WorkOrder");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_resourcerequirement")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement")]
		public XrmEbc.msdyn_resourcerequirement msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.msdyn_resourcerequirement>("msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement");
				this.SetRelatedEntity<XrmEbc.msdyn_resourcerequirement>("msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement", null, value);
				this.OnPropertyChanged("msdyn_resourcerequirement_bookableresourcebooking_ResourceRequirement");
			}
		}
		
		/// <summary>
		/// N:1 team_bookableresourcebooking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_bookableresourcebooking")]
		public XrmEbc.Team team_bookableresourcebooking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.Team>("team_bookableresourcebooking", null);
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_bookableresourcebooking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_bookableresourcebooking")]
		public XrmEbc.TransactionCurrency TransactionCurrency_bookableresourcebooking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.TransactionCurrency>("TransactionCurrency_bookableresourcebooking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TransactionCurrency_bookableresourcebooking");
				this.SetRelatedEntity<XrmEbc.TransactionCurrency>("TransactionCurrency_bookableresourcebooking", null, value);
				this.OnPropertyChanged("TransactionCurrency_bookableresourcebooking");
			}
		}
		
		/// <summary>
		/// N:1 user_bookableresourcebooking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_bookableresourcebooking")]
		public XrmEbc.SystemUser user_bookableresourcebooking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("user_bookableresourcebooking", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public BookableResourceBooking(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["bookableresourcebookingid"] = base.Id;
                        break;
                    case "bookableresourcebookingid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}