//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmEbc
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8586")]
	public enum msdyn_bookingtimestampState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Inactive = 1,
	}
	
	/// <summary>
	/// Tracks status changes of bookings and timestamps the change of the status
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("msdyn_bookingtimestamp")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8586")]
	public partial class msdyn_bookingtimestamp : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public struct Fields
		{
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string ImportSequenceNumber = "importsequencenumber";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string msdyn_Booking = "msdyn_booking";
			public const string msdyn_bookingtimestampId = "msdyn_bookingtimestampid";
			public const string Id = "msdyn_bookingtimestampid";
			public const string msdyn_GenerateJournals = "msdyn_generatejournals";
			public const string msdyn_name = "msdyn_name";
			public const string msdyn_SystemStatus = "msdyn_systemstatus";
			public const string msdyn_TimestampSource = "msdyn_timestampsource";
			public const string msdyn_TimestampTime = "msdyn_timestamptime";
			public const string OverriddenCreatedOn = "overriddencreatedon";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string statecode = "statecode";
			public const string statuscode = "statuscode";
			public const string TimeZoneRuleVersionNumber = "timezoneruleversionnumber";
			public const string UTCConversionTimeZoneCode = "utcconversiontimezonecode";
			public const string VersionNumber = "versionnumber";
			public const string business_unit_msdyn_bookingtimestamp = "business_unit_msdyn_bookingtimestamp";
			public const string lk_msdyn_bookingtimestamp_createdby = "lk_msdyn_bookingtimestamp_createdby";
			public const string lk_msdyn_bookingtimestamp_createdonbehalfby = "lk_msdyn_bookingtimestamp_createdonbehalfby";
			public const string lk_msdyn_bookingtimestamp_modifiedby = "lk_msdyn_bookingtimestamp_modifiedby";
			public const string lk_msdyn_bookingtimestamp_modifiedonbehalfby = "lk_msdyn_bookingtimestamp_modifiedonbehalfby";
			public const string msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking = "msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking";
			public const string team_msdyn_bookingtimestamp = "team_msdyn_bookingtimestamp";
			public const string user_msdyn_bookingtimestamp = "user_msdyn_bookingtimestamp";
		}

		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_bookingtimestamp() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "msdyn_bookingtimestamp";
		
		public const int EntityTypeCode = 10116;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Shows the sequence number of the import that created this record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("importsequencenumber")]
		public System.Nullable<int> ImportSequenceNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("importsequencenumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ImportSequenceNumber");
				this.SetAttributeValue("importsequencenumber", value);
				this.OnPropertyChanged("ImportSequenceNumber");
			}
		}
		
		/// <summary>
		/// Unique identifier of the user who modified the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Unique identifier for Resource Booking associated with Booking Timestamp.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_booking")]
		public Microsoft.Xrm.Sdk.EntityReference msdyn_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("msdyn_booking");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_Booking");
				this.SetAttributeValue("msdyn_booking", value);
				this.OnPropertyChanged("msdyn_Booking");
			}
		}
		
		/// <summary>
		/// Shows the entity instances.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookingtimestampid")]
		public System.Nullable<System.Guid> msdyn_bookingtimestampId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("msdyn_bookingtimestampid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestampId");
				this.SetAttributeValue("msdyn_bookingtimestampid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("msdyn_bookingtimestampId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_bookingtimestampid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.msdyn_bookingtimestampId = value;
			}
		}
		
		/// <summary>
		/// System internal field. Indicates that journals must be generated after saving timestamp from mobile.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_generatejournals")]
		public System.Nullable<bool> msdyn_GenerateJournals
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("msdyn_generatejournals");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_GenerateJournals");
				this.SetAttributeValue("msdyn_generatejournals", value);
				this.OnPropertyChanged("msdyn_GenerateJournals");
			}
		}
		
		/// <summary>
		/// Enter the name of the custom entity.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_name")]
		public string msdyn_name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("msdyn_name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_name");
				this.SetAttributeValue("msdyn_name", value);
				this.OnPropertyChanged("msdyn_name");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_systemstatus")]
		public object msdyn_SystemStatus
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("msdyn_systemstatus");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_SystemStatus");
				this.SetAttributeValue("msdyn_systemstatus", value);
				this.OnPropertyChanged("msdyn_SystemStatus");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_timestampsource")]
		public object msdyn_TimestampSource
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("msdyn_timestampsource");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TimestampSource");
				this.SetAttributeValue("msdyn_timestampsource", value);
				this.OnPropertyChanged("msdyn_TimestampSource");
			}
		}
		
		/// <summary>
		/// 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_timestamptime")]
		public System.Nullable<System.DateTime> msdyn_TimestampTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("msdyn_timestamptime");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_TimestampTime");
				this.SetAttributeValue("msdyn_timestamptime", value);
				this.OnPropertyChanged("msdyn_TimestampTime");
			}
		}
		
		/// <summary>
		/// Shows the date and time that the record was migrated.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overriddencreatedon")]
		public System.Nullable<System.DateTime> OverriddenCreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overriddencreatedon");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OverriddenCreatedOn");
				this.SetAttributeValue("overriddencreatedon", value);
				this.OnPropertyChanged("OverriddenCreatedOn");
			}
		}
		
		/// <summary>
		/// Owner Id
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
		}
		
		/// <summary>
		/// Status of the Booking Timestamp
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<XrmEbc.msdyn_bookingtimestampState> statecode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((XrmEbc.msdyn_bookingtimestampState)(System.Enum.ToObject(typeof(XrmEbc.msdyn_bookingtimestampState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("statecode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value.Value))));
				}
				this.OnPropertyChanged("statecode");
			}
		}
		
		/// <summary>
		/// Reason for the status of the Booking Timestamp
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public object statuscode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("statuscode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("statuscode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("timezoneruleversionnumber")]
		public System.Nullable<int> TimeZoneRuleVersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("timezoneruleversionnumber");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("TimeZoneRuleVersionNumber");
				this.SetAttributeValue("timezoneruleversionnumber", value);
				this.OnPropertyChanged("TimeZoneRuleVersionNumber");
			}
		}
		
		/// <summary>
		/// Shows the time zone code that was in use when the record was created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("utcconversiontimezonecode")]
		public System.Nullable<int> UTCConversionTimeZoneCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("utcconversiontimezonecode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("UTCConversionTimeZoneCode");
				this.SetAttributeValue("utcconversiontimezonecode", value);
				this.OnPropertyChanged("UTCConversionTimeZoneCode");
			}
		}
		
		/// <summary>
		/// Version Number
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_ActivityPointers
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_ActivityPointers")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ActivityPointer> msdyn_bookingtimestamp_ActivityPointers
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ActivityPointer>("msdyn_bookingtimestamp_ActivityPointers", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_ActivityPointers");
				this.SetRelatedEntities<XrmEbc.ActivityPointer>("msdyn_bookingtimestamp_ActivityPointers", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_ActivityPointers");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_adx_alertsubscriptions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_adx_alertsubscriptions")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_alertsubscription> msdyn_bookingtimestamp_adx_alertsubscriptions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_alertsubscription>("msdyn_bookingtimestamp_adx_alertsubscriptions", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_adx_alertsubscriptions");
				this.SetRelatedEntities<XrmEbc.adx_alertsubscription>("msdyn_bookingtimestamp_adx_alertsubscriptions", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_adx_alertsubscriptions");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_adx_inviteredemptions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_adx_inviteredemptions")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_inviteredemption> msdyn_bookingtimestamp_adx_inviteredemptions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_inviteredemption>("msdyn_bookingtimestamp_adx_inviteredemptions", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_adx_inviteredemptions");
				this.SetRelatedEntities<XrmEbc.adx_inviteredemption>("msdyn_bookingtimestamp_adx_inviteredemptions", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_adx_inviteredemptions");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_adx_portalcomments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_adx_portalcomments")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_portalcomment> msdyn_bookingtimestamp_adx_portalcomments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_portalcomment>("msdyn_bookingtimestamp_adx_portalcomments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_adx_portalcomments");
				this.SetRelatedEntities<XrmEbc.adx_portalcomment>("msdyn_bookingtimestamp_adx_portalcomments", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_adx_portalcomments");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_Annotations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_Annotations")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Annotation> msdyn_bookingtimestamp_Annotations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Annotation>("msdyn_bookingtimestamp_Annotations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_Annotations");
				this.SetRelatedEntities<XrmEbc.Annotation>("msdyn_bookingtimestamp_Annotations", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_Annotations");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_Appointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_Appointments")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Appointment> msdyn_bookingtimestamp_Appointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Appointment>("msdyn_bookingtimestamp_Appointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_Appointments");
				this.SetRelatedEntities<XrmEbc.Appointment>("msdyn_bookingtimestamp_Appointments", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_Appointments");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<XrmEbc.AsyncOperation> msdyn_bookingtimestamp_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.AsyncOperation>("msdyn_bookingtimestamp_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_AsyncOperations");
				this.SetRelatedEntities<XrmEbc.AsyncOperation>("msdyn_bookingtimestamp_AsyncOperations", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<XrmEbc.BulkDeleteFailure> msdyn_bookingtimestamp_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.BulkDeleteFailure>("msdyn_bookingtimestamp_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_BulkDeleteFailures");
				this.SetRelatedEntities<XrmEbc.BulkDeleteFailure>("msdyn_bookingtimestamp_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_connections1
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_connections1")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Connection> msdyn_bookingtimestamp_connections1
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Connection>("msdyn_bookingtimestamp_connections1", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_connections1");
				this.SetRelatedEntities<XrmEbc.Connection>("msdyn_bookingtimestamp_connections1", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_connections1");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_connections2
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_connections2")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Connection> msdyn_bookingtimestamp_connections2
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Connection>("msdyn_bookingtimestamp_connections2", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_connections2");
				this.SetRelatedEntities<XrmEbc.Connection>("msdyn_bookingtimestamp_connections2", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_connections2");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_DuplicateBaseRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_DuplicateBaseRecord")]
		public System.Collections.Generic.IEnumerable<XrmEbc.DuplicateRecord> msdyn_bookingtimestamp_DuplicateBaseRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.DuplicateRecord>("msdyn_bookingtimestamp_DuplicateBaseRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_DuplicateBaseRecord");
				this.SetRelatedEntities<XrmEbc.DuplicateRecord>("msdyn_bookingtimestamp_DuplicateBaseRecord", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_DuplicateBaseRecord");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_DuplicateMatchingRecord
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_DuplicateMatchingRecord")]
		public System.Collections.Generic.IEnumerable<XrmEbc.DuplicateRecord> msdyn_bookingtimestamp_DuplicateMatchingRecord
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.DuplicateRecord>("msdyn_bookingtimestamp_DuplicateMatchingRecord", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_DuplicateMatchingRecord");
				this.SetRelatedEntities<XrmEbc.DuplicateRecord>("msdyn_bookingtimestamp_DuplicateMatchingRecord", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_DuplicateMatchingRecord");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_Emails
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_Emails")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Email> msdyn_bookingtimestamp_Emails
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Email>("msdyn_bookingtimestamp_Emails", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_Emails");
				this.SetRelatedEntities<XrmEbc.Email>("msdyn_bookingtimestamp_Emails", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_Emails");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_Faxes
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_Faxes")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Fax> msdyn_bookingtimestamp_Faxes
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Fax>("msdyn_bookingtimestamp_Faxes", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_Faxes");
				this.SetRelatedEntities<XrmEbc.Fax>("msdyn_bookingtimestamp_Faxes", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_Faxes");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_Letters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_Letters")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Letter> msdyn_bookingtimestamp_Letters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Letter>("msdyn_bookingtimestamp_Letters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_Letters");
				this.SetRelatedEntities<XrmEbc.Letter>("msdyn_bookingtimestamp_Letters", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_Letters");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_MailboxTrackingFolders
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_MailboxTrackingFolders")]
		public System.Collections.Generic.IEnumerable<XrmEbc.MailboxTrackingFolder> msdyn_bookingtimestamp_MailboxTrackingFolders
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.MailboxTrackingFolder>("msdyn_bookingtimestamp_MailboxTrackingFolders", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_MailboxTrackingFolders");
				this.SetRelatedEntities<XrmEbc.MailboxTrackingFolder>("msdyn_bookingtimestamp_MailboxTrackingFolders", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_MailboxTrackingFolders");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_msdyn_approvals
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_msdyn_approvals")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_approval> msdyn_bookingtimestamp_msdyn_approvals
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_approval>("msdyn_bookingtimestamp_msdyn_approvals", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_msdyn_approvals");
				this.SetRelatedEntities<XrmEbc.msdyn_approval>("msdyn_bookingtimestamp_msdyn_approvals", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_msdyn_approvals");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_msdyn_bookingalerts
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_msdyn_bookingalerts")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_bookingalert> msdyn_bookingtimestamp_msdyn_bookingalerts
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_bookingalert>("msdyn_bookingtimestamp_msdyn_bookingalerts", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_msdyn_bookingalerts");
				this.SetRelatedEntities<XrmEbc.msdyn_bookingalert>("msdyn_bookingtimestamp_msdyn_bookingalerts", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_msdyn_bookingalerts");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_msdyn_surveyinvites
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_msdyn_surveyinvites")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_surveyinvite> msdyn_bookingtimestamp_msdyn_surveyinvites
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_surveyinvite>("msdyn_bookingtimestamp_msdyn_surveyinvites", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_msdyn_surveyinvites");
				this.SetRelatedEntities<XrmEbc.msdyn_surveyinvite>("msdyn_bookingtimestamp_msdyn_surveyinvites", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_msdyn_surveyinvites");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_PhoneCalls
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_PhoneCalls")]
		public System.Collections.Generic.IEnumerable<XrmEbc.PhoneCall> msdyn_bookingtimestamp_PhoneCalls
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.PhoneCall>("msdyn_bookingtimestamp_PhoneCalls", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_PhoneCalls");
				this.SetRelatedEntities<XrmEbc.PhoneCall>("msdyn_bookingtimestamp_PhoneCalls", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_PhoneCalls");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_PrincipalObjectAttributeAccesses
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_PrincipalObjectAttributeAccesses")]
		public System.Collections.Generic.IEnumerable<XrmEbc.PrincipalObjectAttributeAccess> msdyn_bookingtimestamp_PrincipalObjectAttributeAccesses
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.PrincipalObjectAttributeAccess>("msdyn_bookingtimestamp_PrincipalObjectAttributeAccesses", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_PrincipalObjectAttributeAccesses");
				this.SetRelatedEntities<XrmEbc.PrincipalObjectAttributeAccess>("msdyn_bookingtimestamp_PrincipalObjectAttributeAccesses", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_PrincipalObjectAttributeAccesses");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_ProcessSession
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_ProcessSession")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ProcessSession> msdyn_bookingtimestamp_ProcessSession
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ProcessSession>("msdyn_bookingtimestamp_ProcessSession", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_ProcessSession");
				this.SetRelatedEntities<XrmEbc.ProcessSession>("msdyn_bookingtimestamp_ProcessSession", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_ProcessSession");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_RecurringAppointmentMasters
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_RecurringAppointmentMasters")]
		public System.Collections.Generic.IEnumerable<XrmEbc.RecurringAppointmentMaster> msdyn_bookingtimestamp_RecurringAppointmentMasters
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.RecurringAppointmentMaster>("msdyn_bookingtimestamp_RecurringAppointmentMasters", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_RecurringAppointmentMasters");
				this.SetRelatedEntities<XrmEbc.RecurringAppointmentMaster>("msdyn_bookingtimestamp_RecurringAppointmentMasters", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_RecurringAppointmentMasters");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_ServiceAppointments
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_ServiceAppointments")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ServiceAppointment> msdyn_bookingtimestamp_ServiceAppointments
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ServiceAppointment>("msdyn_bookingtimestamp_ServiceAppointments", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_ServiceAppointments");
				this.SetRelatedEntities<XrmEbc.ServiceAppointment>("msdyn_bookingtimestamp_ServiceAppointments", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_ServiceAppointments");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_SharePointDocumentLocations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_SharePointDocumentLocations")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SharePointDocumentLocation> msdyn_bookingtimestamp_SharePointDocumentLocations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SharePointDocumentLocation>("msdyn_bookingtimestamp_SharePointDocumentLocations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_SharePointDocumentLocations");
				this.SetRelatedEntities<XrmEbc.SharePointDocumentLocation>("msdyn_bookingtimestamp_SharePointDocumentLocations", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_SharePointDocumentLocations");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_SocialActivities
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_SocialActivities")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SocialActivity> msdyn_bookingtimestamp_SocialActivities
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SocialActivity>("msdyn_bookingtimestamp_SocialActivities", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_SocialActivities");
				this.SetRelatedEntities<XrmEbc.SocialActivity>("msdyn_bookingtimestamp_SocialActivities", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_SocialActivities");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_SyncErrors")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SyncError> msdyn_bookingtimestamp_SyncErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SyncError>("msdyn_bookingtimestamp_SyncErrors", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_SyncErrors");
				this.SetRelatedEntities<XrmEbc.SyncError>("msdyn_bookingtimestamp_SyncErrors", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_Tasks
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_Tasks")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Task> msdyn_bookingtimestamp_Tasks
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Task>("msdyn_bookingtimestamp_Tasks", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_Tasks");
				this.SetRelatedEntities<XrmEbc.Task>("msdyn_bookingtimestamp_Tasks", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_Tasks");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingtimestamp_UserEntityInstanceDatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingtimestamp_UserEntityInstanceDatas")]
		public System.Collections.Generic.IEnumerable<XrmEbc.UserEntityInstanceData> msdyn_bookingtimestamp_UserEntityInstanceDatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.UserEntityInstanceData>("msdyn_bookingtimestamp_UserEntityInstanceDatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingtimestamp_UserEntityInstanceDatas");
				this.SetRelatedEntities<XrmEbc.UserEntityInstanceData>("msdyn_bookingtimestamp_UserEntityInstanceDatas", null, value);
				this.OnPropertyChanged("msdyn_bookingtimestamp_UserEntityInstanceDatas");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_msdyn_bookingtimestamp
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_msdyn_bookingtimestamp")]
		public XrmEbc.BusinessUnit business_unit_msdyn_bookingtimestamp
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BusinessUnit>("business_unit_msdyn_bookingtimestamp", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_bookingtimestamp_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_bookingtimestamp_createdby")]
		public XrmEbc.SystemUser lk_msdyn_bookingtimestamp_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_msdyn_bookingtimestamp_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_bookingtimestamp_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_bookingtimestamp_createdonbehalfby")]
		public XrmEbc.SystemUser lk_msdyn_bookingtimestamp_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_msdyn_bookingtimestamp_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_bookingtimestamp_createdonbehalfby");
				this.SetRelatedEntity<XrmEbc.SystemUser>("lk_msdyn_bookingtimestamp_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_msdyn_bookingtimestamp_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_bookingtimestamp_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_bookingtimestamp_modifiedby")]
		public XrmEbc.SystemUser lk_msdyn_bookingtimestamp_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_msdyn_bookingtimestamp_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_msdyn_bookingtimestamp_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_msdyn_bookingtimestamp_modifiedonbehalfby")]
		public XrmEbc.SystemUser lk_msdyn_bookingtimestamp_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_msdyn_bookingtimestamp_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_msdyn_bookingtimestamp_modifiedonbehalfby");
				this.SetRelatedEntity<XrmEbc.SystemUser>("lk_msdyn_bookingtimestamp_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_msdyn_bookingtimestamp_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("msdyn_booking")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking")]
		public XrmEbc.BookableResourceBooking msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BookableResourceBooking>("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking");
				this.SetRelatedEntity<XrmEbc.BookableResourceBooking>("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking", null, value);
				this.OnPropertyChanged("msdyn_bookableresourcebooking_msdyn_bookingtimestamp_Booking");
			}
		}
		
		/// <summary>
		/// N:1 team_msdyn_bookingtimestamp
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_msdyn_bookingtimestamp")]
		public XrmEbc.Team team_msdyn_bookingtimestamp
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.Team>("team_msdyn_bookingtimestamp", null);
			}
		}
		
		/// <summary>
		/// N:1 user_msdyn_bookingtimestamp
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_msdyn_bookingtimestamp")]
		public XrmEbc.SystemUser user_msdyn_bookingtimestamp
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("user_msdyn_bookingtimestamp", null);
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public msdyn_bookingtimestamp(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["msdyn_bookingtimestampid"] = base.Id;
                        break;
                    case "msdyn_bookingtimestampid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}