//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace XrmEbc
{
	
	[System.Runtime.Serialization.DataContractAttribute()]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8586")]
	public enum SLAState
	{
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Draft = 0,
		
		[System.Runtime.Serialization.EnumMemberAttribute()]
		Active = 1,
	}
	
	/// <summary>
	/// Contains information about the tracked service-level KPIs for cases that belong to different customers.
	/// </summary>
	[System.Runtime.Serialization.DataContractAttribute()]
	[Microsoft.Xrm.Sdk.Client.EntityLogicalNameAttribute("sla")]
	[System.CodeDom.Compiler.GeneratedCodeAttribute("CrmSvcUtil", "8.2.1.8586")]
	public partial class SLA : Microsoft.Xrm.Sdk.Entity, System.ComponentModel.INotifyPropertyChanging, System.ComponentModel.INotifyPropertyChanged
	{
		
		public struct Fields
		{
			public const string AllowPauseResume = "allowpauseresume";
			public const string ApplicableFrom = "applicablefrom";
			public const string ApplicableFromPickList = "applicablefrompicklist";
			public const string BusinessHoursId = "businesshoursid";
			public const string ChangedAttributeList = "changedattributelist";
			public const string ComponentState = "componentstate";
			public const string CreatedBy = "createdby";
			public const string CreatedOn = "createdon";
			public const string CreatedOnBehalfBy = "createdonbehalfby";
			public const string Description = "description";
			public const string ExchangeRate = "exchangerate";
			public const string IsDefault = "isdefault";
			public const string IsManaged = "ismanaged";
			public const string ModifiedBy = "modifiedby";
			public const string ModifiedOn = "modifiedon";
			public const string ModifiedOnBehalfBy = "modifiedonbehalfby";
			public const string Name = "name";
			public const string ObjectTypeCode = "objecttypecode";
			public const string OverwriteTime = "overwritetime";
			public const string OwnerId = "ownerid";
			public const string OwningBusinessUnit = "owningbusinessunit";
			public const string OwningTeam = "owningteam";
			public const string OwningUser = "owninguser";
			public const string PrimaryEntityOTC = "primaryentityotc";
			public const string SLAId = "slaid";
			public const string Id = "slaid";
			public const string SLAIdUnique = "slaidunique";
			public const string SLAType = "slatype";
			public const string SolutionId = "solutionid";
			public const string StateCode = "statecode";
			public const string StatusCode = "statuscode";
			public const string TransactionCurrencyId = "transactioncurrencyid";
			public const string VersionNumber = "versionnumber";
			public const string WorkflowId = "workflowid";
			public const string business_unit_slabase = "business_unit_slabase";
			public const string lk_slabase_createdby = "lk_slabase_createdby";
			public const string lk_slabase_createdonbehalfby = "lk_slabase_createdonbehalfby";
			public const string lk_slabase_modifiedby = "lk_slabase_modifiedby";
			public const string lk_slabase_modifiedonbehalfby = "lk_slabase_modifiedonbehalfby";
			public const string slabase_businesshoursid = "slabase_businesshoursid";
			public const string slabase_workflowid = "slabase_workflowid";
			public const string team_slaBase = "team_slaBase";
			public const string TransactionCurrency_SLA = "TransactionCurrency_SLA";
			public const string user_slabase = "user_slabase";
		}

		
		/// <summary>
		/// Default Constructor.
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public SLA() : 
				base(EntityLogicalName)
		{
		}
		
		public const string EntityLogicalName = "sla";
		
		public const int EntityTypeCode = 9750;
		
		public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
		
		public event System.ComponentModel.PropertyChangingEventHandler PropertyChanging;
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanged(string propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
			}
		}
		
		[System.Diagnostics.DebuggerNonUserCode()]
		private void OnPropertyChanging(string propertyName)
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, new System.ComponentModel.PropertyChangingEventArgs(propertyName));
			}
		}
		
		/// <summary>
		/// Select whether this SLA will allow pausing and resuming during the time calculation.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("allowpauseresume")]
		public System.Nullable<bool> AllowPauseResume
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("allowpauseresume");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("AllowPauseResume");
				this.SetAttributeValue("allowpauseresume", value);
				this.OnPropertyChanged("AllowPauseResume");
			}
		}
		
		/// <summary>
		/// Select the field that specifies the date and time from which the SLA items will be calculated for the case record. For example, if you select the Case Created On field, SLA calculation will begin from the time the case is created. 
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("applicablefrom")]
		public string ApplicableFrom
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("applicablefrom");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ApplicableFrom");
				this.SetAttributeValue("applicablefrom", value);
				this.OnPropertyChanged("ApplicableFrom");
			}
		}
		
		/// <summary>
		/// Select the field that specifies the date and time from which the SLA items will be calculated. For example, if you select the Case Created On field, SLA calculation will begin from the time the case is created.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("applicablefrompicklist")]
		public object ApplicableFromPickList
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("applicablefrompicklist");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ApplicableFromPickList");
				this.SetAttributeValue("applicablefrompicklist", value);
				this.OnPropertyChanged("ApplicableFromPickList");
			}
		}
		
		/// <summary>
		/// Choose the business hours for calculating SLA item timelines.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businesshoursid")]
		public Microsoft.Xrm.Sdk.EntityReference BusinessHoursId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("businesshoursid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("BusinessHoursId");
				this.SetAttributeValue("businesshoursid", value);
				this.OnPropertyChanged("BusinessHoursId");
			}
		}
		
		/// <summary>
		/// Type additional information to describe the SLA
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("changedattributelist")]
		public string ChangedAttributeList
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("changedattributelist");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ChangedAttributeList");
				this.SetAttributeValue("changedattributelist", value);
				this.OnPropertyChanged("ChangedAttributeList");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("componentstate")]
		public object ComponentState
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("componentstate");
			}
		}
		
		/// <summary>
		/// Shows who created the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was created. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdon")]
		public System.Nullable<System.DateTime> CreatedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("createdon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference CreatedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("createdonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("CreatedOnBehalfBy");
				this.SetAttributeValue("createdonbehalfby", value);
				this.OnPropertyChanged("CreatedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Type additional information to describe the SLA
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("description")]
		public string Description
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("description");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Description");
				this.SetAttributeValue("description", value);
				this.OnPropertyChanged("Description");
			}
		}
		
		/// <summary>
		/// Exchange rate between the currency associated with the SLA record and the base currency.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("exchangerate")]
		public System.Nullable<decimal> ExchangeRate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<decimal>>("exchangerate");
			}
		}
		
		/// <summary>
		/// Tells whether this SLA is the default one.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("isdefault")]
		public System.Nullable<bool> IsDefault
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("isdefault");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("IsDefault");
				this.SetAttributeValue("isdefault", value);
				this.OnPropertyChanged("IsDefault");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ismanaged")]
		public System.Nullable<bool> IsManaged
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<bool>>("ismanaged");
			}
		}
		
		/// <summary>
		/// Shows who last updated the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedby");
			}
		}
		
		/// <summary>
		/// Shows the date and time when the record was last updated. The date and time are displayed in the time zone selected in Microsoft Dynamics 365 options.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedon")]
		public System.Nullable<System.DateTime> ModifiedOn
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("modifiedon");
			}
		}
		
		/// <summary>
		/// Shows who created the record on behalf of another user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		public Microsoft.Xrm.Sdk.EntityReference ModifiedOnBehalfBy
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("modifiedonbehalfby");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("ModifiedOnBehalfBy");
				this.SetAttributeValue("modifiedonbehalfby", value);
				this.OnPropertyChanged("ModifiedOnBehalfBy");
			}
		}
		
		/// <summary>
		/// Type a descriptive name of the service level agreement (SLA).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("name")]
		public string Name
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<string>("name");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("Name");
				this.SetAttributeValue("name", value);
				this.OnPropertyChanged("Name");
			}
		}
		
		/// <summary>
		/// Choose the entity type that the SLA is defined.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("objecttypecode")]
		public object ObjectTypeCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("objecttypecode");
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("overwritetime")]
		public System.Nullable<System.DateTime> OverwriteTime
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.DateTime>>("overwritetime");
			}
		}
		
		/// <summary>
		/// Enter the user or team who owns the SLA. This field is updated every time the item is assigned to a different user.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("ownerid")]
		public Microsoft.Xrm.Sdk.EntityReference OwnerId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("ownerid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwnerId");
				this.SetAttributeValue("ownerid", value);
				this.OnPropertyChanged("OwnerId");
			}
		}
		
		/// <summary>
		/// Unique identifier for the business unit that owns the record
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		public Microsoft.Xrm.Sdk.EntityReference OwningBusinessUnit
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningbusinessunit");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningBusinessUnit");
				this.SetAttributeValue("owningbusinessunit", value);
				this.OnPropertyChanged("OwningBusinessUnit");
			}
		}
		
		/// <summary>
		/// Unique identifier for the team that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		public Microsoft.Xrm.Sdk.EntityReference OwningTeam
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owningteam");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningTeam");
				this.SetAttributeValue("owningteam", value);
				this.OnPropertyChanged("OwningTeam");
			}
		}
		
		/// <summary>
		/// Unique identifier for the user that owns the record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		public Microsoft.Xrm.Sdk.EntityReference OwningUser
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("owninguser");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("OwningUser");
				this.SetAttributeValue("owninguser", value);
				this.OnPropertyChanged("OwningUser");
			}
		}
		
		/// <summary>
		/// Shows the primary entity that the SLA has been created for.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("primaryentityotc")]
		public System.Nullable<int> PrimaryEntityOTC
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<int>>("primaryentityotc");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("PrimaryEntityOTC");
				this.SetAttributeValue("primaryentityotc", value);
				this.OnPropertyChanged("PrimaryEntityOTC");
			}
		}
		
		/// <summary>
		/// Unique identifier of the SLA.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		public System.Nullable<System.Guid> SLAId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("slaid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SLAId");
				this.SetAttributeValue("slaid", value);
				if (value.HasValue)
				{
					base.Id = value.Value;
				}
				else
				{
					base.Id = System.Guid.Empty;
				}
				this.OnPropertyChanged("SLAId");
			}
		}
		
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaid")]
		public override System.Guid Id
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return base.Id;
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.SLAId = value;
			}
		}
		
		/// <summary>
		/// For internal use only.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slaidunique")]
		public System.Nullable<System.Guid> SLAIdUnique
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("slaidunique");
			}
		}
		
		/// <summary>
		/// Select the type of service level agreement (SLA).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("slatype")]
		public object SLAType
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("slatype");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SLAType");
				this.SetAttributeValue("slatype", value);
				this.OnPropertyChanged("SLAType");
			}
		}
		
		/// <summary>
		/// Unique identifier of the associated solution.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("solutionid")]
		public System.Nullable<System.Guid> SolutionId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<System.Guid>>("solutionid");
			}
		}
		
		/// <summary>
		/// Shows whether the Service Level Agreement (SLA) is active or inactive.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statecode")]
		public System.Nullable<XrmEbc.SLAState> StateCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				Microsoft.Xrm.Sdk.OptionSetValue optionSet = this.GetAttributeValue<Microsoft.Xrm.Sdk.OptionSetValue>("statecode");
				if ((optionSet != null))
				{
					return ((XrmEbc.SLAState)(System.Enum.ToObject(typeof(XrmEbc.SLAState), optionSet.Value)));
				}
				else
				{
					return null;
				}
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StateCode");
				if ((value == null))
				{
					this.SetAttributeValue("statecode", null);
				}
				else
				{
					this.SetAttributeValue("statecode", new Microsoft.Xrm.Sdk.OptionSetValue(((int)(value.Value))));
				}
				this.OnPropertyChanged("StateCode");
			}
		}
		
		/// <summary>
		/// Select the status of the service level agreement (SLA).
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("statuscode")]
		public object StatusCode
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<object>("statuscode");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("StatusCode");
				this.SetAttributeValue("statuscode", value);
				this.OnPropertyChanged("StatusCode");
			}
		}
		
		/// <summary>
		/// Unique identifier of the currency associated with the SLA record.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		public Microsoft.Xrm.Sdk.EntityReference TransactionCurrencyId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("transactioncurrencyid");
			}
		}
		
		/// <summary>
		/// Version number of the SLA.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("versionnumber")]
		public System.Nullable<long> VersionNumber
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<System.Nullable<long>>("versionnumber");
			}
		}
		
		/// <summary>
		/// Workflow associated with the SLA.
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowid")]
		public Microsoft.Xrm.Sdk.EntityReference WorkflowId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetAttributeValue<Microsoft.Xrm.Sdk.EntityReference>("workflowid");
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("WorkflowId");
				this.SetAttributeValue("workflowid", value);
				this.OnPropertyChanged("WorkflowId");
			}
		}
		
		/// <summary>
		/// 1:N adx_alertsubscription_sla_slaid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_alertsubscription_sla_slaid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_alertsubscription> adx_alertsubscription_sla_slaid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_alertsubscription>("adx_alertsubscription_sla_slaid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_alertsubscription_sla_slaid");
				this.SetRelatedEntities<XrmEbc.adx_alertsubscription>("adx_alertsubscription_sla_slaid", null, value);
				this.OnPropertyChanged("adx_alertsubscription_sla_slaid");
			}
		}
		
		/// <summary>
		/// 1:N adx_alertsubscription_sla_slainvokedid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_alertsubscription_sla_slainvokedid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_alertsubscription> adx_alertsubscription_sla_slainvokedid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_alertsubscription>("adx_alertsubscription_sla_slainvokedid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_alertsubscription_sla_slainvokedid");
				this.SetRelatedEntities<XrmEbc.adx_alertsubscription>("adx_alertsubscription_sla_slainvokedid", null, value);
				this.OnPropertyChanged("adx_alertsubscription_sla_slainvokedid");
			}
		}
		
		/// <summary>
		/// 1:N adx_inviteredemption_sla_slaid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_inviteredemption_sla_slaid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_inviteredemption> adx_inviteredemption_sla_slaid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_inviteredemption>("adx_inviteredemption_sla_slaid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_inviteredemption_sla_slaid");
				this.SetRelatedEntities<XrmEbc.adx_inviteredemption>("adx_inviteredemption_sla_slaid", null, value);
				this.OnPropertyChanged("adx_inviteredemption_sla_slaid");
			}
		}
		
		/// <summary>
		/// 1:N adx_inviteredemption_sla_slainvokedid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_inviteredemption_sla_slainvokedid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_inviteredemption> adx_inviteredemption_sla_slainvokedid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_inviteredemption>("adx_inviteredemption_sla_slainvokedid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_inviteredemption_sla_slainvokedid");
				this.SetRelatedEntities<XrmEbc.adx_inviteredemption>("adx_inviteredemption_sla_slainvokedid", null, value);
				this.OnPropertyChanged("adx_inviteredemption_sla_slainvokedid");
			}
		}
		
		/// <summary>
		/// 1:N adx_portalcomment_sla_slaid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_portalcomment_sla_slaid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_portalcomment> adx_portalcomment_sla_slaid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_portalcomment>("adx_portalcomment_sla_slaid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_portalcomment_sla_slaid");
				this.SetRelatedEntities<XrmEbc.adx_portalcomment>("adx_portalcomment_sla_slaid", null, value);
				this.OnPropertyChanged("adx_portalcomment_sla_slaid");
			}
		}
		
		/// <summary>
		/// 1:N adx_portalcomment_sla_slainvokedid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("adx_portalcomment_sla_slainvokedid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.adx_portalcomment> adx_portalcomment_sla_slainvokedid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.adx_portalcomment>("adx_portalcomment_sla_slainvokedid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("adx_portalcomment_sla_slainvokedid");
				this.SetRelatedEntities<XrmEbc.adx_portalcomment>("adx_portalcomment_sla_slainvokedid", null, value);
				this.OnPropertyChanged("adx_portalcomment_sla_slainvokedid");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_account
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_account")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Account> manualsla_account
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Account>("manualsla_account", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_account");
				this.SetRelatedEntities<XrmEbc.Account>("manualsla_account", null, value);
				this.OnPropertyChanged("manualsla_account");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_activitypointer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_activitypointer")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ActivityPointer> manualsla_activitypointer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ActivityPointer>("manualsla_activitypointer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_activitypointer");
				this.SetRelatedEntities<XrmEbc.ActivityPointer>("manualsla_activitypointer", null, value);
				this.OnPropertyChanged("manualsla_activitypointer");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_appointment
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_appointment")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Appointment> manualsla_appointment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Appointment>("manualsla_appointment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_appointment");
				this.SetRelatedEntities<XrmEbc.Appointment>("manualsla_appointment", null, value);
				this.OnPropertyChanged("manualsla_appointment");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_cases
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_cases")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Incident> manualsla_cases
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Incident>("manualsla_cases", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_cases");
				this.SetRelatedEntities<XrmEbc.Incident>("manualsla_cases", null, value);
				this.OnPropertyChanged("manualsla_cases");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_contact")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Contact> manualsla_contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Contact>("manualsla_contact", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_contact");
				this.SetRelatedEntities<XrmEbc.Contact>("manualsla_contact", null, value);
				this.OnPropertyChanged("manualsla_contact");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_email
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_email")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Email> manualsla_email
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Email>("manualsla_email", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_email");
				this.SetRelatedEntities<XrmEbc.Email>("manualsla_email", null, value);
				this.OnPropertyChanged("manualsla_email");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_fax
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_fax")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Fax> manualsla_fax
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Fax>("manualsla_fax", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_fax");
				this.SetRelatedEntities<XrmEbc.Fax>("manualsla_fax", null, value);
				this.OnPropertyChanged("manualsla_fax");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_invoice
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_invoice")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Invoice> manualsla_invoice
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Invoice>("manualsla_invoice", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_invoice");
				this.SetRelatedEntities<XrmEbc.Invoice>("manualsla_invoice", null, value);
				this.OnPropertyChanged("manualsla_invoice");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_lead
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_lead")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Lead> manualsla_lead
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Lead>("manualsla_lead", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_lead");
				this.SetRelatedEntities<XrmEbc.Lead>("manualsla_lead", null, value);
				this.OnPropertyChanged("manualsla_lead");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_letter
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_letter")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Letter> manualsla_letter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Letter>("manualsla_letter", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_letter");
				this.SetRelatedEntities<XrmEbc.Letter>("manualsla_letter", null, value);
				this.OnPropertyChanged("manualsla_letter");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_opportunity
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_opportunity")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Opportunity> manualsla_opportunity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Opportunity>("manualsla_opportunity", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_opportunity");
				this.SetRelatedEntities<XrmEbc.Opportunity>("manualsla_opportunity", null, value);
				this.OnPropertyChanged("manualsla_opportunity");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_phonecall
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_phonecall")]
		public System.Collections.Generic.IEnumerable<XrmEbc.PhoneCall> manualsla_phonecall
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.PhoneCall>("manualsla_phonecall", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_phonecall");
				this.SetRelatedEntities<XrmEbc.PhoneCall>("manualsla_phonecall", null, value);
				this.OnPropertyChanged("manualsla_phonecall");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_quote
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_quote")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Quote> manualsla_quote
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Quote>("manualsla_quote", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_quote");
				this.SetRelatedEntities<XrmEbc.Quote>("manualsla_quote", null, value);
				this.OnPropertyChanged("manualsla_quote");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_salesorder
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_salesorder")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SalesOrder> manualsla_salesorder
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SalesOrder>("manualsla_salesorder", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_salesorder");
				this.SetRelatedEntities<XrmEbc.SalesOrder>("manualsla_salesorder", null, value);
				this.OnPropertyChanged("manualsla_salesorder");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_serviceappointment
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_serviceappointment")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ServiceAppointment> manualsla_serviceappointment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ServiceAppointment>("manualsla_serviceappointment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_serviceappointment");
				this.SetRelatedEntities<XrmEbc.ServiceAppointment>("manualsla_serviceappointment", null, value);
				this.OnPropertyChanged("manualsla_serviceappointment");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_socialactivity
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_socialactivity")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SocialActivity> manualsla_socialactivity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SocialActivity>("manualsla_socialactivity", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_socialactivity");
				this.SetRelatedEntities<XrmEbc.SocialActivity>("manualsla_socialactivity", null, value);
				this.OnPropertyChanged("manualsla_socialactivity");
			}
		}
		
		/// <summary>
		/// 1:N manualsla_task
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("manualsla_task")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Task> manualsla_task
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Task>("manualsla_task", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("manualsla_task");
				this.SetRelatedEntities<XrmEbc.Task>("manualsla_task", null, value);
				this.OnPropertyChanged("manualsla_task");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_approval_sla_slaid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_approval_sla_slaid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_approval> msdyn_approval_sla_slaid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_approval>("msdyn_approval_sla_slaid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_approval_sla_slaid");
				this.SetRelatedEntities<XrmEbc.msdyn_approval>("msdyn_approval_sla_slaid", null, value);
				this.OnPropertyChanged("msdyn_approval_sla_slaid");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_approval_sla_slainvokedid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_approval_sla_slainvokedid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_approval> msdyn_approval_sla_slainvokedid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_approval>("msdyn_approval_sla_slainvokedid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_approval_sla_slainvokedid");
				this.SetRelatedEntities<XrmEbc.msdyn_approval>("msdyn_approval_sla_slainvokedid", null, value);
				this.OnPropertyChanged("msdyn_approval_sla_slainvokedid");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingalert_sla_slaid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingalert_sla_slaid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_bookingalert> msdyn_bookingalert_sla_slaid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_bookingalert>("msdyn_bookingalert_sla_slaid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingalert_sla_slaid");
				this.SetRelatedEntities<XrmEbc.msdyn_bookingalert>("msdyn_bookingalert_sla_slaid", null, value);
				this.OnPropertyChanged("msdyn_bookingalert_sla_slaid");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_bookingalert_sla_slainvokedid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_bookingalert_sla_slainvokedid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_bookingalert> msdyn_bookingalert_sla_slainvokedid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_bookingalert>("msdyn_bookingalert_sla_slainvokedid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_bookingalert_sla_slainvokedid");
				this.SetRelatedEntities<XrmEbc.msdyn_bookingalert>("msdyn_bookingalert_sla_slainvokedid", null, value);
				this.OnPropertyChanged("msdyn_bookingalert_sla_slainvokedid");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_surveyinvite_sla_slaid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_surveyinvite_sla_slaid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_surveyinvite> msdyn_surveyinvite_sla_slaid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_surveyinvite>("msdyn_surveyinvite_sla_slaid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_surveyinvite_sla_slaid");
				this.SetRelatedEntities<XrmEbc.msdyn_surveyinvite>("msdyn_surveyinvite_sla_slaid", null, value);
				this.OnPropertyChanged("msdyn_surveyinvite_sla_slaid");
			}
		}
		
		/// <summary>
		/// 1:N msdyn_surveyinvite_sla_slainvokedid
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("msdyn_surveyinvite_sla_slainvokedid")]
		public System.Collections.Generic.IEnumerable<XrmEbc.msdyn_surveyinvite> msdyn_surveyinvite_sla_slainvokedid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.msdyn_surveyinvite>("msdyn_surveyinvite_sla_slainvokedid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("msdyn_surveyinvite_sla_slainvokedid");
				this.SetRelatedEntities<XrmEbc.msdyn_surveyinvite>("msdyn_surveyinvite_sla_slainvokedid", null, value);
				this.OnPropertyChanged("msdyn_surveyinvite_sla_slainvokedid");
			}
		}
		
		/// <summary>
		/// 1:N sla_account
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_account")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Account> sla_account
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Account>("sla_account", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_account");
				this.SetRelatedEntities<XrmEbc.Account>("sla_account", null, value);
				this.OnPropertyChanged("sla_account");
			}
		}
		
		/// <summary>
		/// 1:N sla_activitypointer
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_activitypointer")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ActivityPointer> sla_activitypointer
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ActivityPointer>("sla_activitypointer", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_activitypointer");
				this.SetRelatedEntities<XrmEbc.ActivityPointer>("sla_activitypointer", null, value);
				this.OnPropertyChanged("sla_activitypointer");
			}
		}
		
		/// <summary>
		/// 1:N sla_Annotation
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_Annotation")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Annotation> sla_Annotation
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Annotation>("sla_Annotation", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_Annotation");
				this.SetRelatedEntities<XrmEbc.Annotation>("sla_Annotation", null, value);
				this.OnPropertyChanged("sla_Annotation");
			}
		}
		
		/// <summary>
		/// 1:N sla_appointment
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_appointment")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Appointment> sla_appointment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Appointment>("sla_appointment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_appointment");
				this.SetRelatedEntities<XrmEbc.Appointment>("sla_appointment", null, value);
				this.OnPropertyChanged("sla_appointment");
			}
		}
		
		/// <summary>
		/// 1:N sla_cases
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_cases")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Incident> sla_cases
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Incident>("sla_cases", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_cases");
				this.SetRelatedEntities<XrmEbc.Incident>("sla_cases", null, value);
				this.OnPropertyChanged("sla_cases");
			}
		}
		
		/// <summary>
		/// 1:N sla_contact
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_contact")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Contact> sla_contact
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Contact>("sla_contact", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_contact");
				this.SetRelatedEntities<XrmEbc.Contact>("sla_contact", null, value);
				this.OnPropertyChanged("sla_contact");
			}
		}
		
		/// <summary>
		/// 1:N sla_email
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_email")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Email> sla_email
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Email>("sla_email", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_email");
				this.SetRelatedEntities<XrmEbc.Email>("sla_email", null, value);
				this.OnPropertyChanged("sla_email");
			}
		}
		
		/// <summary>
		/// 1:N sla_entitlement
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_entitlement")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Entitlement> sla_entitlement
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Entitlement>("sla_entitlement", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_entitlement");
				this.SetRelatedEntities<XrmEbc.Entitlement>("sla_entitlement", null, value);
				this.OnPropertyChanged("sla_entitlement");
			}
		}
		
		/// <summary>
		/// 1:N sla_entitlementtemplate
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_entitlementtemplate")]
		public System.Collections.Generic.IEnumerable<XrmEbc.EntitlementTemplate> sla_entitlementtemplate
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.EntitlementTemplate>("sla_entitlementtemplate", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_entitlementtemplate");
				this.SetRelatedEntities<XrmEbc.EntitlementTemplate>("sla_entitlementtemplate", null, value);
				this.OnPropertyChanged("sla_entitlementtemplate");
			}
		}
		
		/// <summary>
		/// 1:N sla_fax
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_fax")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Fax> sla_fax
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Fax>("sla_fax", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_fax");
				this.SetRelatedEntities<XrmEbc.Fax>("sla_fax", null, value);
				this.OnPropertyChanged("sla_fax");
			}
		}
		
		/// <summary>
		/// 1:N sla_invoice
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_invoice")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Invoice> sla_invoice
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Invoice>("sla_invoice", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_invoice");
				this.SetRelatedEntities<XrmEbc.Invoice>("sla_invoice", null, value);
				this.OnPropertyChanged("sla_invoice");
			}
		}
		
		/// <summary>
		/// 1:N sla_lead
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_lead")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Lead> sla_lead
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Lead>("sla_lead", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_lead");
				this.SetRelatedEntities<XrmEbc.Lead>("sla_lead", null, value);
				this.OnPropertyChanged("sla_lead");
			}
		}
		
		/// <summary>
		/// 1:N sla_letter
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_letter")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Letter> sla_letter
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Letter>("sla_letter", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_letter");
				this.SetRelatedEntities<XrmEbc.Letter>("sla_letter", null, value);
				this.OnPropertyChanged("sla_letter");
			}
		}
		
		/// <summary>
		/// 1:N sla_opportunity
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_opportunity")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Opportunity> sla_opportunity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Opportunity>("sla_opportunity", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_opportunity");
				this.SetRelatedEntities<XrmEbc.Opportunity>("sla_opportunity", null, value);
				this.OnPropertyChanged("sla_opportunity");
			}
		}
		
		/// <summary>
		/// 1:N sla_phonecall
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_phonecall")]
		public System.Collections.Generic.IEnumerable<XrmEbc.PhoneCall> sla_phonecall
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.PhoneCall>("sla_phonecall", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_phonecall");
				this.SetRelatedEntities<XrmEbc.PhoneCall>("sla_phonecall", null, value);
				this.OnPropertyChanged("sla_phonecall");
			}
		}
		
		/// <summary>
		/// 1:N sla_quote
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_quote")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Quote> sla_quote
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Quote>("sla_quote", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_quote");
				this.SetRelatedEntities<XrmEbc.Quote>("sla_quote", null, value);
				this.OnPropertyChanged("sla_quote");
			}
		}
		
		/// <summary>
		/// 1:N sla_salesorder
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_salesorder")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SalesOrder> sla_salesorder
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SalesOrder>("sla_salesorder", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_salesorder");
				this.SetRelatedEntities<XrmEbc.SalesOrder>("sla_salesorder", null, value);
				this.OnPropertyChanged("sla_salesorder");
			}
		}
		
		/// <summary>
		/// 1:N sla_serviceappointment
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_serviceappointment")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ServiceAppointment> sla_serviceappointment
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ServiceAppointment>("sla_serviceappointment", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_serviceappointment");
				this.SetRelatedEntities<XrmEbc.ServiceAppointment>("sla_serviceappointment", null, value);
				this.OnPropertyChanged("sla_serviceappointment");
			}
		}
		
		/// <summary>
		/// 1:N sla_slaitem_slaId
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_slaitem_slaId")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SLAItem> sla_slaitem_slaId
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SLAItem>("sla_slaitem_slaId", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_slaitem_slaId");
				this.SetRelatedEntities<XrmEbc.SLAItem>("sla_slaitem_slaId", null, value);
				this.OnPropertyChanged("sla_slaitem_slaId");
			}
		}
		
		/// <summary>
		/// 1:N sla_socialactivity
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_socialactivity")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SocialActivity> sla_socialactivity
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SocialActivity>("sla_socialactivity", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_socialactivity");
				this.SetRelatedEntities<XrmEbc.SocialActivity>("sla_socialactivity", null, value);
				this.OnPropertyChanged("sla_socialactivity");
			}
		}
		
		/// <summary>
		/// 1:N SLA_SyncErrors
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("SLA_SyncErrors")]
		public System.Collections.Generic.IEnumerable<XrmEbc.SyncError> SLA_SyncErrors
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.SyncError>("SLA_SyncErrors", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("SLA_SyncErrors");
				this.SetRelatedEntities<XrmEbc.SyncError>("SLA_SyncErrors", null, value);
				this.OnPropertyChanged("SLA_SyncErrors");
			}
		}
		
		/// <summary>
		/// 1:N sla_task
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("sla_task")]
		public System.Collections.Generic.IEnumerable<XrmEbc.Task> sla_task
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.Task>("sla_task", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("sla_task");
				this.SetRelatedEntities<XrmEbc.Task>("sla_task", null, value);
				this.OnPropertyChanged("sla_task");
			}
		}
		
		/// <summary>
		/// 1:N slabase_AsyncOperations
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("slabase_AsyncOperations")]
		public System.Collections.Generic.IEnumerable<XrmEbc.AsyncOperation> slabase_AsyncOperations
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.AsyncOperation>("slabase_AsyncOperations", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("slabase_AsyncOperations");
				this.SetRelatedEntities<XrmEbc.AsyncOperation>("slabase_AsyncOperations", null, value);
				this.OnPropertyChanged("slabase_AsyncOperations");
			}
		}
		
		/// <summary>
		/// 1:N slabase_BulkDeleteFailures
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("slabase_BulkDeleteFailures")]
		public System.Collections.Generic.IEnumerable<XrmEbc.BulkDeleteFailure> slabase_BulkDeleteFailures
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.BulkDeleteFailure>("slabase_BulkDeleteFailures", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("slabase_BulkDeleteFailures");
				this.SetRelatedEntities<XrmEbc.BulkDeleteFailure>("slabase_BulkDeleteFailures", null, value);
				this.OnPropertyChanged("slabase_BulkDeleteFailures");
			}
		}
		
		/// <summary>
		/// 1:N slabase_ProcessSessions
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("slabase_ProcessSessions")]
		public System.Collections.Generic.IEnumerable<XrmEbc.ProcessSession> slabase_ProcessSessions
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.ProcessSession>("slabase_ProcessSessions", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("slabase_ProcessSessions");
				this.SetRelatedEntities<XrmEbc.ProcessSession>("slabase_ProcessSessions", null, value);
				this.OnPropertyChanged("slabase_ProcessSessions");
			}
		}
		
		/// <summary>
		/// 1:N slabase_userentityinstancedatas
		/// </summary>
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("slabase_userentityinstancedatas")]
		public System.Collections.Generic.IEnumerable<XrmEbc.UserEntityInstanceData> slabase_userentityinstancedatas
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntities<XrmEbc.UserEntityInstanceData>("slabase_userentityinstancedatas", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("slabase_userentityinstancedatas");
				this.SetRelatedEntities<XrmEbc.UserEntityInstanceData>("slabase_userentityinstancedatas", null, value);
				this.OnPropertyChanged("slabase_userentityinstancedatas");
			}
		}
		
		/// <summary>
		/// N:1 business_unit_slabase
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningbusinessunit")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("business_unit_slabase")]
		public XrmEbc.BusinessUnit business_unit_slabase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.BusinessUnit>("business_unit_slabase", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("business_unit_slabase");
				this.SetRelatedEntity<XrmEbc.BusinessUnit>("business_unit_slabase", null, value);
				this.OnPropertyChanged("business_unit_slabase");
			}
		}
		
		/// <summary>
		/// N:1 lk_slabase_createdby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_slabase_createdby")]
		public XrmEbc.SystemUser lk_slabase_createdby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_slabase_createdby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_slabase_createdonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("createdonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_slabase_createdonbehalfby")]
		public XrmEbc.SystemUser lk_slabase_createdonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_slabase_createdonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_slabase_createdonbehalfby");
				this.SetRelatedEntity<XrmEbc.SystemUser>("lk_slabase_createdonbehalfby", null, value);
				this.OnPropertyChanged("lk_slabase_createdonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 lk_slabase_modifiedby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_slabase_modifiedby")]
		public XrmEbc.SystemUser lk_slabase_modifiedby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_slabase_modifiedby", null);
			}
		}
		
		/// <summary>
		/// N:1 lk_slabase_modifiedonbehalfby
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("modifiedonbehalfby")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("lk_slabase_modifiedonbehalfby")]
		public XrmEbc.SystemUser lk_slabase_modifiedonbehalfby
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("lk_slabase_modifiedonbehalfby", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("lk_slabase_modifiedonbehalfby");
				this.SetRelatedEntity<XrmEbc.SystemUser>("lk_slabase_modifiedonbehalfby", null, value);
				this.OnPropertyChanged("lk_slabase_modifiedonbehalfby");
			}
		}
		
		/// <summary>
		/// N:1 slabase_businesshoursid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("businesshoursid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("slabase_businesshoursid")]
		public XrmEbc.Calendar slabase_businesshoursid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.Calendar>("slabase_businesshoursid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("slabase_businesshoursid");
				this.SetRelatedEntity<XrmEbc.Calendar>("slabase_businesshoursid", null, value);
				this.OnPropertyChanged("slabase_businesshoursid");
			}
		}
		
		/// <summary>
		/// N:1 slabase_workflowid
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("workflowid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("slabase_workflowid")]
		public XrmEbc.Workflow slabase_workflowid
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.Workflow>("slabase_workflowid", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("slabase_workflowid");
				this.SetRelatedEntity<XrmEbc.Workflow>("slabase_workflowid", null, value);
				this.OnPropertyChanged("slabase_workflowid");
			}
		}
		
		/// <summary>
		/// N:1 team_slaBase
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owningteam")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("team_slaBase")]
		public XrmEbc.Team team_slaBase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.Team>("team_slaBase", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("team_slaBase");
				this.SetRelatedEntity<XrmEbc.Team>("team_slaBase", null, value);
				this.OnPropertyChanged("team_slaBase");
			}
		}
		
		/// <summary>
		/// N:1 TransactionCurrency_SLA
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("transactioncurrencyid")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("TransactionCurrency_SLA")]
		public XrmEbc.TransactionCurrency TransactionCurrency_SLA
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.TransactionCurrency>("TransactionCurrency_SLA", null);
			}
		}
		
		/// <summary>
		/// N:1 user_slabase
		/// </summary>
		[Microsoft.Xrm.Sdk.AttributeLogicalNameAttribute("owninguser")]
		[Microsoft.Xrm.Sdk.RelationshipSchemaNameAttribute("user_slabase")]
		public XrmEbc.SystemUser user_slabase
		{
			[System.Diagnostics.DebuggerNonUserCode()]
			get
			{
				return this.GetRelatedEntity<XrmEbc.SystemUser>("user_slabase", null);
			}
			[System.Diagnostics.DebuggerNonUserCode()]
			set
			{
				this.OnPropertyChanging("user_slabase");
				this.SetRelatedEntity<XrmEbc.SystemUser>("user_slabase", null, value);
				this.OnPropertyChanged("user_slabase");
			}
		}
		
		/// <summary>
		/// Constructor for populating via LINQ queries given a LINQ anonymous type
		/// <param name="anonymousType">LINQ anonymous type.</param>
		/// </summary>
		[System.Diagnostics.DebuggerNonUserCode()]
		public SLA(object anonymousType) : 
				this()
		{
            foreach (var p in anonymousType.GetType().GetProperties())
            {
                var value = p.GetValue(anonymousType, null);
                var name = p.Name.ToLower();
            
                if (name.EndsWith("enum") && value.GetType().BaseType == typeof(System.Enum))
                {
                    value = new Microsoft.Xrm.Sdk.OptionSetValue((int) value);
                    name = name.Remove(name.Length - "enum".Length);
                }
            
                switch (name)
                {
                    case "id":
                        base.Id = (System.Guid)value;
                        Attributes["slaid"] = base.Id;
                        break;
                    case "slaid":
                        var id = (System.Nullable<System.Guid>) value;
                        if(id == null){ continue; }
                        base.Id = id.Value;
                        Attributes[name] = base.Id;
                        break;
                    case "formattedvalues":
                        // Add Support for FormattedValues
                        FormattedValues.AddRange((Microsoft.Xrm.Sdk.FormattedValueCollection)value);
                        break;
                    default:
                        Attributes[name] = value;
                        break;
                }
            }
		}
	}
}